# Configuración general del proyecto
project_name: Intro Agentes AI

# Credenciales
credenciales:
  dwh_onpremise:
    service_name: ''
    ip: ''
    port: ''
    usuario: ''
    password: ''

  dwh_cloud:
    dsn_con: ''
    usuario: ''
    password: ''

# Rutas
rutas:
  ruta_onedrive: ''
  ruta_instantclient: ''

# Notificaciones
notificaciones:
  slack: ''