research_task:
  description: >
    Conduct a thorough research about {topic}
    Make sure you find any interesting and relevant information given
    the current year is {current_year}.
  expected_output: >
    A list with 5 bullet points of the most relevant information about {topic} with a link to the source.
  agent: researcher

reporting_task:
  description: >
    Review the context you got and expand each topic into a full section for a report.
    Make sure the report is detailed and contains any and all relevant information.
  expected_output: >
    A fully fledged report with the main topics enumerated, each with a full section of information.
    Formatted as markdown without '```' and use emojis to make it more engaging.
    Give the report in spanish.

    The final structure is:

    # Informe de AI LLMs

    ## Nombre de la noticia 1
    Descripción de la noticia 
    - Idea principal 1
    - Idea principal 2
    **Movie:** Película recomendada 

    Fuente: [Fuente](https://www.fuente.com)
    ---
    
  agent: reporting_analyst
